import pandas as pd
import numpy as np

print(np.random.seed(101))
print("-"*50)
df = pd.DataFrame(np.random.randn(5,4), index="A B C D E".split(),columns="W X Y Z".split())
print(df)
print("-"*50)
print()
print(df["W"])
print()
print(type(df))
print()
print(df[["W", "Z"]])
print()
df["new"] = df["W"] + df["X"]
print(df)
print()
print(df.drop("new", axis=1))
print()
print(df)
print()
print(df.drop("new", axis=1, inplace=True))
print(df)
print()
print(df.loc["A", "W"])
print(df.loc["A"])
print()
print(df.loc[["A", "B"], ["X", "Y", "Z"]])
print()
print(df.iloc[0:1, 1:])
print()
print(df.iloc[2:4, 1:])